47 diagrama classes
UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza pull request #58
Opened 2023-10-01 16:31 UTC by GabriellyAssuncao

## Mudanças

- Criação do artefato diagrama de classes.

## Comentários adicionais

-

2023-10-03 00:16 UTC, Neitan2001 requested changes

2023-10-03 00:16 UTC, Neitan2001 commented on docs/Assets/diagrama-de-classes.png
Essa seta do DataType está correta? Essa seta é a de interface. A seta correta seria a de depência, o segundo print que coloquei
![image](https://github.com/UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza/assets/64803935/19fd0e4b-28bf-4f18-bbdb-d4c8cd8780b6)
![image](https://github.com/UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza/assets/64803935/823d639d-6059-4890-91a3-47ce70d4de94)

2023-10-03 00:16 UTC, Neitan2001 commented on docs/Assets/diagrama-de-classes.png
O pedido pode ser uma classe de associação da compra que nem está no print de exemplo abaixo
![image](https://github.com/UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza/assets/64803935/1d54d03c-7f33-4baa-aade-ed5026a791b0)
![image](https://github.com/UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza/assets/64803935/73e0d9a7-8a11-4f61-b7f6-c866c36bcc31)

2023-10-03 00:16 UTC, Neitan2001 commented on docs/Assets/diagrama-de-classes.png
Seria bom dar uma olhada para ver se essa herança de carrinho (super) para pedido faz sentido. Se fizer, o atributo de Produto no pedido não é necessário pois em carrinho tem Produtos e um pedido vindo do carrinho teria mais de um produto. Essa herança pode não fazer sentido também, tem que dar uma repensada
![image](https://github.com/UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza/assets/64803935/4ce57d10-e0c2-4fc4-b79c-fdc9f684e848)

2023-10-03 13:14 UTC, brunna-martins commented on docs/Modelagem/2.1.1.1.DiagramaClasses.md
> +| 01/10/2023 | 1.2    | Adicionando diagrama e conclusão                 | [Gabrielly Assunção](https://github.com/GabriellyAssuncao) | |
Mudança realizada.

2023-10-03 13:15 UTC, brunna-martins commented on docs/Modelagem/2.1.1.1.DiagramaClasses.md
> + <img src="https://raw.githubusercontent.com/UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza/main/docs/Assets/Dia_Classe_Exe.jpg">
Imagem funcionando.

2023-10-03 13:15 UTC, brunna-martins commented on docs/Assets/diagrama-de-classes.png
Corrigido.

2023-10-03 13:17 UTC, brunna-martins commented
Mudanças solicitadas foram realizadas.

2023-10-03 13:20 UTC, brunna-martins approved these changes

2023-10-04 12:27 UTC, Neitan2001 approved these changes

2023-10-04 12:29 UTC, merged